version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1944
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:10
    container_name: weather-api-flyway
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/weather -user=postgres -password=1944  -connectRetries=10 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/weather
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1944
    ports:
      - "8080:8080"

volumes:
  pgdata:
